import { readFileSync } from 'fs';
const lines = readFileSync('.env.vercel', 'utf8').split(/\r?\n/);
const get = (k) => { const l = lines.find((x) => x.startsWith(k + '=')); return l ? l.slice(k.length + 1).replace(/^"|"$/g, '') : ''; };
const url = get('POSTGRES_URL_NON_POOLING');
const pg = await import('pg');
const c = new pg.default.Client({ connectionString: url });
await c.connect();
const { rows } = await c.query("SELECT material_id, data::text IS NOT NULL as has_data FROM knowledge_graphs LIMIT 5");
console.log('kg rows:', rows.length);
for (const r of rows) console.log(' -', r.material_id.slice(0,8), 'has_data:', r.has_data);
await c.end();